### ISSUE TITLE
Session randomly disconnecting during playback

### ISSUE THREAD

**Issue by hugues999** [pannal/plex-for-kodi#169] opened 2024-11-05 16:19 UTC
## Description:

When watching videos, sometimes the session with Plex seems to disconnect. It happens almost every time after a few minutes (anywhere from 5mins to say 30mins). I can tell because:
- The playback session disappears from the Activities page in Plex Web
- In the Kodi stream info, it mentions `Info not available (session not found)`

Things to note:
- The playback still works just fine. The main problem is that if I stop the video, I lose its progress, it resets back to Unwatched (or wherever it was before the session disconnected).
- As a workaround, if I seek forward or backward, the session reconnects.
- I'm playing from my home server in my LAN with a very fast wired connection, so I don't think it's a networking issue? Also it doesn't seem to happen with similar addons like PlexKodiConnect and Composite.

I captured a log of a failed session, but there is nothing that seems relevant to the disconnect. I guess I would need to enable debug mode, but the problem is that it's very hard to reproduce reliably. I can try if that helps!

Thanks!

## Details:
- Add-on version: 0.8.0-beta5
- Kodi version: 21.1
- OS Platform: CoreElec 21.1.1-Omega
- Hardware: Ugoos AM6B Plus, Amlogic S922X

## Checklist
- [ ] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels

**Comment by pannal** [comment] 2024-11-05 16:58
That would definitely help, yes. PM4K is simply a client to the Plex server. It pings its timeline state regularly.

This seems very specific to your setup. Not sure if I can help you really. A look at debug logs would be good, though.

Also please try to eliminate any intermediates such as any reverse proxies (swag, nginx).

**Comment by rushuna86** [comment] 2024-11-09 11:31
I'm using the exact same set up and this is also happening, thought I'm getting a full disconnect from playback like source has DC

**Comment by pannal** [comment] 2024-11-09 13:03
Great. Still no logs.

**Comment by rushuna86** [comment] 2024-11-09 22:31
[log-2024-11-09-22.30.47.zip](https://github.com/user-attachments/files/17689547/log-2024-11-09-22.30.47.zip)

sorry here is the debug log from [plex-for-kodi]. happens at the very end it fully disconnects the playback. Also another thing I noticed during playback Dashboard on the Plex server shows the video is Paused the whole time it was being played.

**Comment by rushuna86** [comment] 2024-11-09 23:00
@pannal i found it, this is the commit where it started happening e9fe65f, i checkout to the commit right before it and it doesn't happen 810797e. so during playback it seems like the client is not sending the plex server any updates on it's playback status, so on the dashboard it shows the the session as paused. and by default plex server kicks sessions that are paused at 5mins. This is why OP sees the diconnect at 5mins, because the plex server is closing the session.

**Comment by pannal** [comment] 2024-11-09 23:13
Oh. Yeah, that makes sense. Let me debug this change.

**Comment by pannal** [comment] 2024-11-09 23:15
Weird. It shouldn't block the thread for more than 2 seconds.

**Comment by pannal** [comment] 2024-11-09 23:20
Ah no, judging from your log the thread crashes on:
```
2024-11-09 22:22:25.100 T:10231   error <general>: _________________________________________________________________________________
2024-11-09 22:22:25.101 T:10231   error <general>: script.plexmod: ERROR: Exception when trying to check for embedded subtitles
2024-11-09 22:22:25.101 T:10231   error <general>:     Traceback (most recent call last):
2024-11-09 22:22:25.101 T:10231   error <general>:       File "/storage/.kodi/addons/script.plexmod/lib/player.py", line 475, in onAVStarted
2024-11-09 22:22:25.101 T:10231   error <general>:         self.dialog.setSubtitles()
2024-11-09 22:22:25.101 T:10231   error <general>:       File "/storage/.kodi/addons/script.plexmod/lib/windows/seekdialog.py", line 1437, in setSubtitles
2024-11-09 22:22:25.101 T:10231   error <general>:         self.handler.setSubtitles(do_sleep=do_sleep, honor_forced_subtitles_override=honor_forced_subtitles_override,
2024-11-09 22:22:25.101 T:10231   error <general>:       File "/storage/.kodi/addons/script.plexmod/lib/player.py", line 718, in setSubtitles
2024-11-09 22:22:25.101 T:10231   error <general>:         subs = self.player.video.selectedSubtitleStream(
2024-11-09 22:22:25.101 T:10231   error <general>:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-09 22:22:25.101 T:10231   error <general>:       File "/storage/.kodi/addons/script.plexmod/lib/_included_packages/plexnet/video.py", line 169, in selectedSubtitleStream
2024-11-09 22:22:25.101 T:10231   error <general>:         deselect_subtitles is not None and str(selas.languageCode) in deselect_subtitles and \
2024-11-09 22:22:25.101 T:10231   error <general>:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-09 22:22:25.101 T:10231   error <general>:     TypeError: argument of type 'bool' is not iterable
2024-11-09 22:22:25.101 T:10231   error <general>: _________________________________________________________________________________
2024-11-09 22:22:25.101 T:10231   error <general>: `
```

**Comment by pannal** [comment] 2024-11-09 23:30
Please set PM4K to DEBUG and post your logs again, thank you!

**Comment by pannal** [comment] 2024-11-09 23:34
This commit might fix this, although I still need debug logs: https://github.com/pannal/plex-for-kodi/commit/2effba952cc4db234e5cfeb4b04782373084ac36

**Comment by rushuna86** [comment] 2024-11-09 23:46
[log-2024-11-09-23.44.56.zip](https://github.com/user-attachments/files/17689723/log-2024-11-09-23.44.56.zip)
still same issue, server is seeing the video playback as paused and closing session. I have PM4K debug on, so if i'm uploading the wrong log just let me know where to location of the log you are after.

**Comment by pannal** [comment] 2024-11-09 23:52
Huh. You're not using path mapping judging by your logs. I thought this was related to it, but it can't be if you're not using it. Investigating.

Also not getting anything interesting from your logs. Apart from seeing _way_ too few timeline requests, which explains why the stream is detected as paused.

**Comment by pannal** [comment] 2024-11-09 23:58
Still not seeing DEBUG messages inside your logs, though. You might need to set Kodi to DEBUG as well.

**Comment by rushuna86** [comment] 2024-11-10 00:37
[log-2024-11-10-00.37.21.zip](https://github.com/user-attachments/files/17689787/log-2024-11-10-00.37.21.zip)
that's with PM4K and Kodi Debug on. And no not using path mapping

**Comment by pannal** [comment] 2024-11-10 02:14
Can you post a log with the version that works?

**Comment by rushuna86** [comment] 2024-11-10 02:37
commit 810797e
[log-2024-11-10-02.37.09.zip](https://github.com/user-attachments/files/17689953/log-2024-11-10-02.37.09.zip)

**Comment by pannal** [comment] 2024-11-10 02:42
Interesting, thank you! There's definitely something wrong with the timeline requests.

**Comment by pannal** [comment] 2024-11-10 02:42
Might take a while to debug, though. Feel free to stay at the older beta.

**Comment by pannal** [comment] 2024-11-10 14:00
Hmm, I currently have no idea how this issue got introduced with that commit.

**Comment by pannal** [comment] 2024-11-10 14:31
And I can't reproduce this.

**Comment by pannal** [comment] 2024-11-10 14:32
Are you sure you've tried my latest commit?

**Comment by pannal** [comment] 2024-11-10 14:42
Hmm, that's a problem in your log:
```
4-11-10 09:44:06.039 T:4021    error <general>: CCurlFile::CReadState::FillBuffer - (0xe4f3d468) Failed: Failure when receiving data from the peer(56)
2024-11-10 09:44:06.039 T:4021  warning <general>: CFileCache::Process - <https://xxxxxx.plex.direct:32400/library/parts/69659/1730141102/?X-Plex-Token=xxxxxxxxx&X-Plex-Client-Profile-Name=Generic&X-Plex-Client-Identifier=80016188-7db6-49d7-b4eb-ef8a1ba05e4d> source read returned 0! Will retry
2024-11-10 09:44:08.039 T:4021  warning <general>: CCurlFile::CReadState::FillBuffer - (0xe4f3d468) Reconnect, (re)try 1
2024-11-10 09:44:08.049 T:4021    error <general>: CCurlFile::CReadState::FillBuffer - (0xe4f3d468) Failed: HTTP returned code 503
```

But that's the server.

**Comment by pannal** [comment] 2024-11-10 15:02
![image](https://github.com/user-attachments/assets/75aedb4f-ce40-43a0-b2cc-e298f61ba207)
Does disabling this fix the issue?

**Comment by rushuna86** [comment] 2024-11-10 20:19
> ![image](https://private-user-images.githubusercontent.com/1359593/384699503-75aedb4f-ce40-43a0-b2cc-e298f61ba207.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNzAyNjcsIm5iZiI6MTczMTI2OTk2NywicGF0aCI6Ii8xMzU5NTkzLzM4NDY5OTUwMy03NWFlZGI0Zi1jZTQwLTQzYTAtYjJjYy1lMjk4ZjYxYmEyMDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTBUMjAxOTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODNhODY0M2I4MjZkMGQ3YjgzMjkxYzcyN2Y5ZGE3Yzk3YzBjYTU4MDc2YTkwNGJhNjY5YmJiODNiMmI1M2EwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gQMZf95mrkSbMzxiv0RWVkdAlwMx53wZb3JbKlBMmXo) Does disabling this fix the issue?

disabling that fixes it. video no longer shows as paused in dashboard

**Comment by pannal** [comment] 2024-11-10 20:39
Damn. That CoreELEC bug sure isn't worth the hassle. @bowlingbeeg any ideas?

@rushuna86 did you recently update your CE? Do you see any audio issues when resuming from a known resume point?

**Comment by rushuna86** [comment] 2024-11-10 20:55
> Damn. That CoreELEC bug sure isn't worth the hassle. @bowlingbeeg any ideas?
> 
> @rushuna86 did you recently update your CE? Do you see any audio issues when resuming from a known resume point?

yes recently updated CE i use the CPM build, and did occasionally very rarely though saw where the audio was out of sync after restarting video. But it was easily fixed just exit n restart video, and it was all good. but right now even with that option disabled PM4K working like it always has, so no biggie having it disabled.

**Comment by pannal** [comment] 2024-11-10 21:25
Yeah. This CE fix is getting complicated to maintain.

**Comment by mvanbaak** [comment] 2024-11-10 22:16
> Yeah. This CE fix is getting complicated to maintain.

I just watched a movie (using CPM A9 build on an ugoos am6b+, which i installed this morning, it was released 2 days ago), paused a couple of times, and I had this seek fix disabled.
Results:
 * audio sometimes takes like half a second to get back after unpause/resume but it is in sync when it comes back
 * tautulli always showed the correct state
 * When we finished watching the movie, it was marked as watched in plex

So besides the half a second with only video and no audio, there were 0 issues

**Comment by rushuna86** [comment] 2024-11-10 22:34
Yeah after I disabled it the dashboard shows video as playing and so the disconnects are gone. I'll just keep it disabled tbh I never saw or even knew the purpose of it

**Comment by pannal** [comment] 2024-11-10 22:42
The fix(es) were regarding:
https://github.com/pannal/plex-for-kodi/pull/117
https://github.com/pannal/plex-for-kodi/pull/135

It might not be necessary anymore, though. I think I'll disable them by default for the next version.

**Comment by pannal** [comment] 2024-11-10 23:32
I don't get why this would break with https://github.com/pannal/plex-for-kodi/commit/e9fe65f4437b2c5050ca75d5936ae0df91280d55, though.

**Comment by rushuna86** [comment] 2024-11-10 23:45
yeah not sure on that one, but i tested every commit, all was working up until that commit, was where it stopped showing video playback as playing and plex server kicking the session.

**Comment by pannal** [comment] 2024-11-11 00:05
Please try the latest commit if you can. Both with the fix enabled and without it. Please post logs for both. I have a sneaky suspicion.

Edit: It only adds more logging

**Comment by rushuna86** [comment] 2024-11-11 00:10
> Please try the latest commit if you can. Both with the fix enabled and without it. Please post logs for both. I have a sneaky suspicion.
> 
> Edit: It only adds more logging

i'll update and provide you the logs when I get home from work. Will be 6 hours from now.

**Comment by pannal** [comment] 2024-11-11 00:20
Thanks! Pushed more logging just now, as well.

**Comment by rushuna86** [comment] 2024-11-11 08:19
@pannal updated to newest commit with more logging. set server to kicked paused session at 1minute. here are the logs. alternate seek enabled shows as expected paused status during playback and server kicks the session a bit over 1minute into playback. disabled continues to play as usual.
[alternate seek enabled.zip](https://github.com/user-attachments/files/17699284/alternate.seek.enabled.zip)
[alternate seek disabled.zip](https://github.com/user-attachments/files/17699286/alternate.seek.disabled.zip)

**Comment by rushuna86** [comment] 2024-11-11 08:29
@pannal i found what's causing the issue. with the alternate seek enabled it only bugs out if you have subtitles enabled. if you turn off subtitles it behaves normal, shows as playing on dashboard. and the subtitles has to be set already before playback starts, ie like forced eng subs for foreign language. enabling subs midway through playback doesn't cause an issue.

**Comment by pannal** [comment] 2024-11-11 14:32
Yeah, and it only happens if you start something fresh, without a resume point, right?

**Comment by pannal** [comment] 2024-11-11 14:37
Pushed a possible fix, please try it out!

**Comment by rushuna86** [comment] 2024-11-11 16:47
@pannal it happens with stuff with resume points as well. and yes the push has fixed the issue.

**Comment by pannal** [comment] 2024-11-11 18:10
Interesting. Thank you for testing!

**Comment by rushuna86** [comment] 2024-11-11 21:22
@pannal actually i take that back it's still there. it's actually the opposite of what you said. so if you start a brand new movie/show and have subtitle it works fine now, but if the show has a resume point and you enable subtitles on the overview screen before playback, when playback starts it will show as paused.

**Comment by rushuna86** [comment] 2024-11-11 21:57
@pannal new logs if you want to keep working on it, otherwise having the alternate seek off is a perfectly good solution. seems like too much hassle.1ish second of no audio is not end of the world.
[resume point,alternate seek off,subtitle on - works fine.zip](https://github.com/user-attachments/files/17708496/resume.point.alternate.seek.off.subtitle.on.-.works.fine.zip)
[fresh start,alternate seek on,subtitle on - works fine.zip](https://github.com/user-attachments/files/17708497/fresh.start.alternate.seek.on.subtitle.on.-.works.fine.zip)
[fresh start,alternate seek off,subtitle on - works fine.zip](https://github.com/user-attachments/files/17708499/fresh.start.alternate.seek.off.subtitle.on.-.works.fine.zip)
[resume point,alternate seek on,subtitle on - doesnt work.zip](https://github.com/user-attachments/files/17708500/resume.point.alternate.seek.on.subtitle.on.-.doesnt.work.zip)

**Comment by pannal** [comment] 2024-11-11 22:25
Wait, I have an idea.

**Comment by pannal** [comment] 2024-11-11 22:30
Pushed another commit, which reverts the change from 10 days ago "Player/SeekDialog: Move embedded subtitle fix slightly". Does that help?

**Comment by pannal** [comment] 2024-11-11 22:31
> @pannal actually i take that back it's still there. it's actually the opposite of what you said. so if you start a brand new movie/show and have subtitle it works fine now, but if the show has a resume point and you enable subtitles on the overview screen before playback, when playback starts it will show as paused.

This is _specific_ to embedded subtitles, right? Shouldn't happen with externals.

**Comment by rushuna86** [comment] 2024-11-11 22:41
These are all embedded subtitles either PGS or SRT. I'll have to test it later tonight have already left for work. Will let you know if fixes it once I do.

**Comment by pannal** [comment] 2024-11-11 22:48
Thank you for sticking with me on this!

**Comment by rushuna86** [comment] 2024-11-12 07:52
it's working properly now even with alternate seek enabled. both on resume point and fresh start with subtitles on.

**Comment by mvanbaak** [comment] 2024-11-13 22:07
> > Yeah. This CE fix is getting complicated to maintain.
> 
> I just watched a movie (using CPM A9 build on an ugoos am6b+, which i installed this morning, it was released 2 days ago), paused a couple of times, and I had this seek fix disabled. Results:
> 
> * audio sometimes takes like half a second to get back after unpause/resume but it is in sync when it comes back
> * tautulli always showed the correct state
> * When we finished watching the movie, it was marked as watched in plex
> 
> So besides the half a second with only video and no audio, there were 0 issues

I have to get back to this.
Today I had two movies with resume points that acted totally weird with this CoreElec fix DISABLED.
They did start from the beginning, no adio, and the image showed the frame of the resume point.
When hitting the stop button on my remote, the movies were marked as unwatched.
A third movie also had a resume point, but I only resumed it after re-enabling this coroelec seek setting (and the timer sitting under it at 350ms)
This movie did resume correctly.

Me and the wife wanted to watch this movie, so I quickly changed the setting back on and things worked so I did not wait to see if it resolved itself, nor do I have logs. Sorry for that.

**Comment by pannal** [comment] 2024-12-20 09:37
@mvanbaak does this still happen with 0.8.0-beta6?

**Closed as completed** 2024-12-30 02:33 UTC
Labels: bug, CoreELEC, Solved in next beta
