### ISSUE TITLE
192 kHz Flac Audio doesn't play

### ISSUE THREAD

**Issue by MrKamsar** [pannal/plex-for-kodi#130] opened 2024-07-11 19:40 UTC
## Details:
- Add-on version: 0.7.8
- Kodi version: 20.1
- OS Platform: Android
- Hardware: Shield TV

## Checklist
- [ ] No log available
- [ ] Don't understand

**Comment by MrKamsar** [comment] 2024-07-11 19:41
0.7.8 broke 192kbps flac

**Comment by pannal** [comment] 2024-07-11 22:42
Specific to 192kbps? Or flac in general?

A log file would be great.

**Comment by MrKamsar** [comment] 2024-07-11 23:12
Specific to 192kbps 48 and 96 is OK.   I'll try to get a. log file

**Comment by MrKamsar** [comment] 2024-07-12 01:34
I'm  running kodi 21.0 Omega not 20.1.  I can't  figure out how to get a
log file off of the shield.  192 plays fine on 0.7.6 but o. 0.7.8 it just
scrolls thru the album titles and stops.

**Comment by pannal** [comment] 2024-07-12 06:38
You mean kHz not kbps, right?

**Comment by pannal** [comment] 2024-07-12 07:19
Was able to reproduce, will be fixed in the next beta, hopefully arriving on the weekend (see forum thread).

**Comment by pannal** [comment] 2024-07-12 07:42
Are you sure this ever worked? Sampling rate directplay was limited to <192 kHz since 2018.

Edit: It probably always transcoded

**Comment by MrKamsar** [comment] 2024-07-12 13:10
Yes 192kbps flac files play with 0.7.6.

**Comment by MrKamsar** [comment] 2024-07-12 13:11
Awesome, thanks for the update!

**Comment by pannal** [comment] 2024-07-12 19:57
Try this: https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21/481208/2393

**Closed as completed** 2024-07-17 14:06 UTC
Labels: bug, good first issue, Solved in next beta

**Comment by MrKamsar** [comment] 2024-08-22 15:37
Plex 7.9 is working well.  Thanks
