### ISSUE TITLE
After returns from suspend mode freezing Plex in CoreElec

### ISSUE THREAD

**Issue by evertonmdz** [pannal/plex-for-kodi#124] opened 2024-07-04 12:24 UTC
## Details:
Add-on version: 0.7.8
Kodi version: 21.0 Omega
OS Platform: CoreElec Kernel 5.4.210
Hardware: Tox3 S905x4/c2
CoreELEC-Amlogic-ne.aarch64-21.0-Omega-Generic.img.gz

## Checklist
- [ x ] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels

![20240704_091115](https://github.com/pannal/plex-for-kodi/assets/8215931/8eefa711-3250-4958-bd11-e35489df4025)
[log-2024-07-04-12.11.53.zip](https://github.com/user-attachments/files/16098827/log-2024-07-04-12.11.53.zip)
[log-2024-07-04-12.17.12.zip](https://github.com/user-attachments/files/16098828/log-2024-07-04-12.17.12.zip)

Congratulations on supporting the Addon to this day, even on CoreElec, thanks to you we have a usable Plex on Kodi! I think it's much better than using Kodi or Plex on Android.

**Comment by pannal** [comment] 2024-07-04 14:59
Yeah, the network connectivity isn't there, yet, at that state:
```
2024-05-02 00:34:36.466 T:1607    error <general>: _________________________________________________________________________________
2024-05-02 00:34:36.466 T:1607    error <general>: script.plex: ERROR: 
2024-05-02 00:34:36.466 T:1607    error <general>:     Traceback (most recent call last):
2024-05-02 00:34:36.466 T:1607    error <general>:       File "/storage/.kodi/addons/script.plexmod/lib/_included_packages/plexnet/plexserver.py", line 236, in query
2024-05-02 00:34:36.466 T:1607    error <general>:         response = method(url, **kwargs)
2024-05-02 00:34:36.466 T:1607    error <general>:                    ^^^^^^^^^^^^^^^^^^^^^
2024-05-02 00:34:36.466 T:1607    error <general>:       File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 602, in get
2024-05-02 00:34:36.466 T:1607    error <general>:         return self.request("GET", url, **kwargs)
2024-05-02 00:34:36.466 T:1607    error <general>:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-02 00:34:36.466 T:1607    error <general>:       File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 589, in request
2024-05-02 00:34:36.466 T:1607    error <general>:         resp = self.send(prep, **send_kwargs)
2024-05-02 00:34:36.466 T:1607    error <general>:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-02 00:34:36.466 T:1607    error <general>:       File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 703, in send
2024-05-02 00:34:36.466 T:1607    error <general>:         r = adapter.send(request, **kwargs)
2024-05-02 00:34:36.466 T:1607    error <general>:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-02 00:34:36.466 T:1607    error <general>:       File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 486, in send
2024-05-02 00:34:36.466 T:1607    error <general>:         resp = conn.urlopen(
2024-05-02 00:34:36.466 T:1607    error <general>:                ^^^^^^^^^^^^^
2024-05-02 00:34:36.466 T:1607    error <general>:       File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 790, in urlopen
2024-05-02 00:34:36.466 T:1607    error <general>:         response = self._make_request(
2024-05-02 00:34:36.466 T:1607    error <general>:                    ^^^^^^^^^^^^^^^^^^^
2024-05-02 00:34:36.466 T:1607    error <general>:       File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 467, in _make_request
2024-05-02 00:34:36.466 T:1607    error <general>:         self._validate_conn(conn)
2024-05-02 00:34:36.466 T:1607    error <general>:       File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 1096, in _validate_conn
2024-05-02 00:34:36.466 T:1607    error <general>:         conn.connect()
2024-05-02 00:34:36.466 T:1607    error <general>:       File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 611, in connect
2024-05-02 00:34:36.466 T:1607    error <general>:         self.sock = sock = self._new_conn()
2024-05-02 00:34:36.466 T:1607    error <general>:                            ^^^^^^^^^^^^^^^^
2024-05-02 00:34:36.466 T:1607    error <general>:       File "/storage/.kodi/addons/script.plexmod/lib/_included_packages/plexnet/asyncadapter.py", line 157, in _new_conn
2024-05-02 00:34:36.466 T:1607    error <general>:         sock = self.create_connection(
2024-05-02 00:34:36.466 T:1607    error <general>:                ^^^^^^^^^^^^^^^^^^^^^^^
2024-05-02 00:34:36.466 T:1607    error <general>:       File "/storage/.kodi/addons/script.plexmod/lib/_included_packages/plexnet/asyncadapter.py", line 118, in create_connection
2024-05-02 00:34:36.466 T:1607    error <general>:         for msg in self._connect(sock, sa):
2024-05-02 00:34:36.466 T:1607    error <general>:       File "/storage/.kodi/addons/script.plexmod/lib/_included_packages/plexnet/asyncadapter.py", line 138, in _connect
2024-05-02 00:34:36.466 T:1607    error <general>:         self._check_timeout()  # this should be done at the beginning of each loop
2024-05-02 00:34:36.466 T:1607    error <general>:         ^^^^^^^^^^^^^^^^^^^^^
2024-05-02 00:34:36.466 T:1607    error <general>:       File "/storage/.kodi/addons/script.plexmod/lib/_included_packages/plexnet/asyncadapter.py", line 88, in _check_timeout
2024-05-02 00:34:36.466 T:1607    error <general>:         raise TimeoutException('connection timed out')
2024-05-02 00:34:36.466 T:1607    error <general>:     plexnet.asyncadapter.TimeoutException: connection timed out
2024-05-02 00:34:36.466 T:1607    error <general>: _________________________________________________________________________________
```

After which PM4K basically dies and takes your OS with it.

I have a couple of areas I can try to address this in.

You could try setting "Maximum wait time for network" from "Off" to something higher, maybe that fixes it already (Kodi Settings/System).

**Comment by pannal** [comment] 2024-07-04 15:48
Also I think our retry handling never worked for Timeout Errors. The next beta will have a potential fix for this.

**Comment by evertonmdz** [comment] 2024-07-04 15:51
> Also I think our retry handling never worked for Timeout Errors. The next beta will have a potential fix for this.

wow, very good to know, unfortunately the timeout  "Maximum wait time for network" didn't work, I set it to 30 seconds, which is the maximum limit, and it didn't work, it keeps crashing.

**Comment by pannal** [comment] 2024-07-05 07:39
You can try this, it might have fixed timeout error retry logic: [script.plexmod.zip](https://github.com/user-attachments/files/16106598/script.plexmod.zip)

(This already uses the new templating engine, so the first start will be slow, and, in that work in progress beta, every start will be slow once you enable DEBUG)

**Comment by evertonmdz** [comment] 2024-07-05 13:13
> You can try this, it might have fixed timeout error retry logic: [script.plexmod.zip](https://github.com/user-attachments/files/16106598/script.plexmod.zip)
> 
> (This already uses the new templating engine, so the first start will be slow, and, in that work in progress beta, every start will be slow once you enable DEBUG)

It didn't work, it still collapses after coming back from sleep mode, sometimes it comes back partially as was the case in the last log below, but if you try to navigate in some sections it goes into a loading loop like the photo in the post. But thank you for trying to help, as I said earlier, this doesn't happen on Android TV, only on Coreelec! Let's see if more people appear with this problem, a "temporary solution" is not to turn off the TV box.
[log-2024-07-05-13.05.04.zip](https://github.com/user-attachments/files/16110102/log-2024-07-05-13.05.04.zip)
[log-2024-07-05-13.09.18.zip](https://github.com/user-attachments/files/16110103/log-2024-07-05-13.09.18.zip)

**Comment by pannal** [comment] 2024-07-05 13:44
Hmm, I don't see any Tracebacks/Errors in your latest logs anymore, regarding this issue.

**Comment by pannal** [comment] 2024-07-05 13:49
With the latest version I've posted, can you exit PM4K, start it again, and then it works?

If so, I could try implementing a "Restart plugin after wakeup" option for "System->Action on Sleep event". Or simply a "Exit PM4K".

**Comment by evertonmdz** [comment] 2024-07-05 14:01
> With the latest version I've posted, can you exit PM4K, start it again, and then it works?
> 
> If so, I could try implementing a "Restart plugin after wakeup" option for "System->Action on Sleep event". Or simply a "Exit PM4K".

I understand, but here it keeps crashing lol, I think I'll use the TV box's Android TV for now, it doesn't have these problems and stuttering problem.
I tried to click on exiting the addon after returning from sleep mode, it stayed on this screen and froze, it just keeps loading without stopping in a loop 
[log-2024-07-05-13.57.03.zip](https://github.com/user-attachments/files/16110587/log-2024-07-05-13.57.03.zip)
![20240705_105558](https://github.com/pannal/plex-for-kodi/assets/8215931/1b308666-9960-4698-9b6c-4aa6ea94207d)

**Comment by pannal** [comment] 2024-07-05 14:11
OK wait, maybe I can circumvent this.

I'm seeing:
```
2024-07-05 10:55:11.027 T:1120  warning <general>: PLEX.download: Server unreachable at: https://192-168-1-4.c62f760bf6874b0ba9129a4a6f81c2df.plex.direct:32400
2024-07-05 10:55:11.027 T:1120  warning <general>: PLEX.download: HTTPSConnectionPool(host='192-168-1-4.c62f760bf6874b0ba9129a4a6f81c2df.plex.direct', port=32400): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4c18d3b0>: Failed to resolve '192-168-1-4.c62f760bf6874b0ba9129a4a6f81c2df.plex.direct' ([Errno -3] Temporary failure in name resolution)"))
```
from a different addon (I guess PKC) and 

```
2024-07-05 10:55:11.299 T:1122     info <general>: PLEX.service: Server is online and ready
```
about 200ms afterwards.

I'll try and implement a "Action on Wake" setting, with the options: "None", "Restart PM4K" as well as "Wait for X seconds" where X is 5, 10, 15, ... .

From what I can gather, 1 should be enough, easily. Bear with me.

Edit: Oh, might have to be 15 seconds for your specific case.

**Comment by evertonmdz** [comment] 2024-07-05 14:29
> OK wait, maybe I can circumvent this.
> 
> I'm seeing:
> 
> ```
> 2024-07-05 10:55:11.027 T:1120  warning <general>: PLEX.download: Server unreachable at: https://192-168-1-4.c62f760bf6874b0ba9129a4a6f81c2df.plex.direct:32400
> 2024-07-05 10:55:11.027 T:1120  warning <general>: PLEX.download: HTTPSConnectionPool(host='192-168-1-4.c62f760bf6874b0ba9129a4a6f81c2df.plex.direct', port=32400): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4c18d3b0>: Failed to resolve '192-168-1-4.c62f760bf6874b0ba9129a4a6f81c2df.plex.direct' ([Errno -3] Temporary failure in name resolution)"))
> ```
> 
> from a different addon (I guess PKC) and
> 
> ```
> 2024-07-05 10:55:11.299 T:1122     info <general>: PLEX.service: Server is online and ready
> ```
> 
> about 200ms afterwards.
> 
> I'll try and implement a "Action on Wake" setting, with the options: "None", "Restart PM4K" as well as "Wait for X seconds" where X is 5, 10, 15, ... .
> 
> From what I can gather, 1 should be enough, easily. Bear with me.
> 
> Edit: Oh, might have to be 15 seconds for your specific case.

Yes, PKC doesn't show any errors because it runs connected to Kodi, I even tried to disable it, but it doesn't help PM4K. 
 Yes yes, I understand, I'm not charging you anything hehe, especially because you don't have a CoreElec installation, there's no need to be in a hurry about this, because as I said, the TV box runs both Android TV and CoreElec, I only use CoreElec because it is lighter.  But perhaps these implementations that you have made can work.
I even tested its beta on AndroidTv too, these new implementations were really cool.  Congratulations.

**Comment by pannal** [comment] 2024-07-05 14:59
Try this please: [script.plexmod.zip](https://github.com/user-attachments/files/16111150/script.plexmod.zip)

There's a new setting under PM4K->Settings->System called "Action on Wake event". Please try setting this to 10, 15, 30 seconds and see whether this fixes the issue.

> Yes, PKC doesn't show any errors

Ah I guess "PLEX.download" is a different addon. 
Edit: Hmm, "PLEX.service" seems to be PKC, though. It simply seems to recover better than we  are.

**Comment by evertonmdz** [comment] 2024-07-05 15:12
> Try this please: [script.plexmod.zip](https://github.com/user-attachments/files/16111150/script.plexmod.zip)
> 
> There's a new setting under PM4K->Settings->System called "Action on Wake event". Please try setting this to 10, 15, 30 seconds and see whether this fixes the issue.
> 
> > Yes, PKC doesn't show any errors
> 
> Ah I guess "PLEX.download" is a different addon. Edit: Hmm, "PLEX.service" seems to be PKC, though. It simply seems to recover better than we are.

Lol, congratulations on the quick solution, it was resolved with just a 5 second delay, as I use a network cable, so the connection is quick to resume. No more problems in suspend mode! 
I'll leave the log if you want to see how it went, but it's normal now!
[log-2024-07-05-15.09.19.zip](https://github.com/user-attachments/files/16111291/log-2024-07-05-15.09.19.zip)

**Comment by pannal** [comment] 2024-07-05 15:15
Awesome. I forgot to increase the theme version in that build, so your UI isn't up to date.

Please use this: [script.plexmod.zip](https://github.com/user-attachments/files/16111332/script.plexmod.zip)

**Comment by pannal** [comment] 2024-07-05 15:15
Closing!

**Closed as completed by pannal** 2024-07-05 15:15 UTC
Labels: CoreELEC, Networking, Sleep/Suspend, Solved in next beta

**Comment by pannal** [comment] 2024-07-05 15:25
I'll make the five second wait a default for CoreELEC, I think.

**Comment by evertonmdz** [comment] 2024-07-21 13:17
> I'll make the five second wait a default for CoreELEC, I think.

Good morning, after some tests I realized that it is better to use Restart PM4K and the restart function only works if it is on the PM4K home screen, if it is within a film menu or within the film synopsis screen itself, etc., it does not work o Restart PM4K, it gets stuck inside the menu with (...) loading screen, after suspending.
[log-2024-07-21-13.11.04.zip](https://github.com/user-attachments/files/16324559/log-2024-07-21-13.11.04.zip)

**Comment by pannal** [comment] 2024-07-21 13:45
You seem to be using this test release: https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21/481208/2466
Please update to beta15: https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21/481208/2469

And try again, then please post the logs, thank you!

**Comment by pannal** [comment] 2024-07-21 13:57
If it still doesn't work, try this: [script.plexmod.zip](https://github.com/user-attachments/files/16324705/script.plexmod.zip)
It _might_ fix that.

**Comment by evertonmdz** [comment] 2024-07-21 14:30
> If it still doesn't work, try this: [script.plexmod.zip](https://github.com/user-attachments/files/16324705/script.plexmod.zip) It _might_ fix that.

It didn't work in either of the 2 versions, it only moves 1 menu back, only working when it's in Home.
[log-2024-07-21-14.28.42.zip](https://github.com/user-attachments/files/16324844/log-2024-07-21-14.28.42.zip)

**Comment by pannal** [comment] 2024-07-21 14:58
Huh: `Activate of window '13002' refused because there are active modal dialogs` - did you have a dialog open?

**Comment by evertonmdz** [comment] 2024-07-21 15:37
> Huh: `Activate of window '13002' refused because there are active modal dialogs` - did you have a dialog open?

I was responding through the power menu, now mapping a control button to suspend, but now there is a gray screen after returning from suspend. 
[log-2024-07-21-15.35.52.zip](https://github.com/user-attachments/files/16325117/log-2024-07-21-15.35.52.zip)
![20240721_123422](https://github.com/user-attachments/assets/710039af-9189-46bf-a00f-cce3fcfee320)

**Comment by pannal** [comment] 2024-07-21 16:13
I think I got it fixed: https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21/481208/2475

**Comment by pannal** [comment] 2024-07-21 16:18
Well at least the "doesn't restart when not in home view" issue.

**Comment by evertonmdz** [comment] 2024-07-21 16:58
> Well at least the "doesn't restart when not in home view" issue.

Yes, when it is on the initial screen there are no problems, it restarts PM4K normally, but I tested it here again, within a film menu and within a film in the synopsis part it still just keeps returning to the previous screen instead of restarting PM4K, in the new Beta 15.1! However, it is usable, you just have to remember to go back to home when turning off the TV. However, it no longer gave the gray screen from the previous post.

What I forgot to mention, as it just goes back to the previous menu, it bugs PM4K and the Kodi system, making you have to restart CoreElec. The only time that PM4K returns from suspension works without crashing the entire system is when it is on Home.

A possible solution would also be to add a Key Map to force PM4K to restart when it crashes like this. So you don't have to restart CoreElec.
[log-2024-07-21-16.53.26.zip](https://github.com/user-attachments/files/16325372/log-2024-07-21-16.53.26.zip)

**Comment by pannal** [comment] 2024-07-21 20:36
beta15.2 should fix this, tested using episodes window.

> within a film menu and within a film in the synopsis part

You're putting your device to sleep while an item is playing? Oo

**Comment by evertonmdz** [comment] 2024-07-21 21:24
> beta15.2 should fix this, tested using episodes window.
> 
> > within a film menu and within a film in the synopsis part
> 
> You're putting your device to sleep while an item is playing? Oo

Sorry for the way I said it, it was inside the film library and inside Pre Play, where you choose subtitles, audio, etc. I tested it here, it didn't work, it came back from sleep mode and was stuck on the PM4K Home screen. (same with zip "Reuploaded zip (23:40 CEST)"
[log-2024-07-21-21.22.02.zip](https://github.com/user-attachments/files/16326118/log-2024-07-21-21.22.02.zip)

![20240721_174325](https://github.com/user-attachments/assets/508a97bb-a400-4594-bdb2-215e29f3ee04)
![20240721_174337](https://github.com/user-attachments/assets/a16f0dac-d9d5-4367-b47a-a1b175a2084b)

**Comment by pannal** [comment] 2024-07-22 12:06
Try this, please: [script.plexmod.zip](https://github.com/user-attachments/files/16332574/script.plexmod.zip)

**Comment by evertonmdz** [comment] 2024-07-22 12:17
> Try this, please: [script.plexmod.zip](https://github.com/user-attachments/files/16332574/script.plexmod.zip)

Good morning, it didn't work, it just went back from the pre play screen to the library movie screen and stuck PM4K and Coreelec.
[log-2024-07-22-12.17.07.zip](https://github.com/user-attachments/files/16332812/log-2024-07-22-12.17.07.zip)

**Comment by pannal** [comment] 2024-07-22 12:29
And this only happens when navigating to a library, then to an item? What if you go directly to an item on Home, without navigating to the library, does it work then?

**Comment by evertonmdz** [comment] 2024-07-22 12:32
> And this only happens when navigating to a library, then to an item? What if you go directly to an item on Home, without navigating to the library, does it work then?

Yes, only happens when navigating to a library, then to an item! If a go directly to an item on Home, without navigating to the library, it worked without any problems.

**Comment by pannal** [comment] 2024-07-22 12:39
Yeah this is very hard to debug for me, because I can't reproduce the state your PM4K is in, after sleep. Seems like any API calls made after wake time out, which causes this massive hang. Try this, please: [script.plexmod.zip](https://github.com/user-attachments/files/16333177/script.plexmod.zip)

**Comment by evertonmdz** [comment] 2024-07-22 12:58
> Yeah this is very hard to debug for me, because I can't reproduce the state your PM4K is in, after sleep. Seems like any API calls made after wake time out, which causes this massive hang. Try this, please: [script.plexmod.zip](https://github.com/user-attachments/files/16333177/script.plexmod.zip)

It finally worked, congratulations on the hard work!
[log-2024-07-22-12.57.46.zip](https://github.com/user-attachments/files/16333542/log-2024-07-22-12.57.46.zip)

**Comment by pannal** [comment] 2024-07-22 13:03
Awesome, thank you for testing all those attempts!

**Comment by pannal** [comment] 2024-07-22 13:04
BTW why is that?

> Good morning, after some tests I realized that it is better to use Restart PM4K

**Comment by evertonmdz** [comment] 2024-07-22 13:19
> BTW why is that?
> 
> > Good morning, after some tests I realized that it is better to use Restart PM4K

With the timer when it wasn't on home, coreelec crashed too.

**Comment by pannal** [comment] 2024-07-22 13:27
Oh OK. I probably could've fixed that the same way I fixed the restart functionality. Maybe another time.

**Comment by evertonmdz** [comment] 2024-07-22 13:32
> Oh OK. I probably could've fixed that the same way I fixed the restart functionality. Maybe another time.

No problem, Restart PM4K is perfect now, you can leave it as default for now, I'll leave the log for you to see when I suspended it within the "pre play movie" using the 5 seconds.
[log-2024-07-22-13.31.27.zip](https://github.com/user-attachments/files/16334183/log-2024-07-22-13.31.27.zip)

**Comment by pannal** [comment] 2024-07-22 14:13
So this is Home -> Movie or Home -> Library -> Movie? Did you press anything after waking it up?

**Comment by evertonmdz** [comment] 2024-07-22 14:15
> So this is Home -> Movie or Home -> Library -> Movie? Did you press anything after waking it up?

Yes, in this sequence, I pressed return on the control after waiting for the timer. However, if I press the home button at the top it also results in (...) eternal loading.

**Comment by pannal** [comment] 2024-07-22 14:26
Hmm. Can't reproduce this at all. I'll let this sit for a while, maybe I just can't see it right now.

**Comment by evertonmdz** [comment] 2024-07-22 14:31
> Hmm. Não dá para reproduzir isso. Vou deixar isso descansar por um tempo, talvez eu simplesmente não possa vê-lo agora.

Yes CoreElec is problematic with PM4K, I let the system suspend every 2 hours, so I don't mind leaving it on Restart PM4K. I left the function on the coreelec if I turn off the TV, stop movie playback and just turn off the TV. So he doesn't keep suspending corelec all the time.

**Comment by pannal** [comment] 2024-07-22 16:22
I had an idea, try this please: [script.plexmod.zip](https://github.com/user-attachments/files/16336892/script.plexmod.zip)

It adds an option to "Action on Sleep event" called "Go to Home screen", which now is default on CoreELEC. Please try if that works together with the wake delay.

**Comment by evertonmdz** [comment] 2024-07-22 16:40
> I had an idea, try this please: [script.plexmod.zip](https://github.com/user-attachments/files/16336892/script.plexmod.zip)
> 
> It adds an option to "Action on Sleep event" called "Go to Home screen", which now is default on CoreELEC. Please try if that works together with the wake delay.

He went to Home, however, It didn't work, PM4K keeps crashing, it goes (...) in the middle of the screen, if you try to navigate to something it crashes for good. I tried changing it to 10secs but it didn't work either. That's why I said that Restart PM4K was better. Hehehe 
[log-2024-07-22-16.34.27.zip](https://github.com/user-attachments/files/16337088/log-2024-07-22-16.34.27.zip)
[log-2024-07-22-16.37.35.zip](https://github.com/user-attachments/files/16337089/log-2024-07-22-16.37.35.zip)

**Comment by evertonmdz** [comment] 2024-07-23 12:24
> I had an idea, try this please: [script.plexmod.zip](https://github.com/user-attachments/files/16336892/script.plexmod.zip)
> 
> It adds an option to "Action on Sleep event" called "Go to Home screen", which now is default on CoreELEC. Please try if that works together with the wake delay.

Good morning, after some tests I realized that Restart PM4K, after returning from suspension, does not play any item in the series tab, only the movies, causing me to have to exit PM4K and open it again to be able to play the series (tvshows). 
[log-2024-07-23-12.21.42.zip](https://github.com/user-attachments/files/16348709/log-2024-07-23-12.21.42.zip)

**Comment by pannal** [comment] 2024-07-23 12:38
Yeah seems like you lose your UserID: `APP.PlaybackManager, something's wrong: ServerUUID: 55e6182e44ce78585c2c8de92be6b0d3deb9871f, UserID: None`. I'll check.

**Comment by pannal** [comment] 2024-07-23 12:47
Yes, the callback for the account initialization times out after 15 seconds. The restart is happening too fast after wakeup.

**Comment by evertonmdz** [comment] 2024-07-23 13:00
> Sim, o retorno de chamada para a inicialização da conta expira após 15 segundos. A reinicialização está acontecendo muito rápido após o despertar.

But strange, because the film library works normally lol, and when Plex opens it already has normal internet too!

**Comment by pannal** [comment] 2024-07-23 13:02
Yes, because the playback settings only apply to Episodes/Shows. And the playback settings are user-aware, so they require the current user ID, which you don't have because the request timed out.

Try this, please: [script.plexmod.zip](https://github.com/user-attachments/files/16349173/script.plexmod.zip)

It might even fix the wake-sleep issue with waiting for 5 seconds. I believe no timeout was set for certain requests, so depending on your system, that could hang for minutes (which might be what you were experiencing).

Additionally it retries the myplex account query 4 times if it times out.

Edit: To be clear, this is the _earliest_ request made after restarting.

**Comment by evertonmdz** [comment] 2024-07-23 13:12
> Yes, because the playback settings only apply to Episodes/Shows. And the playback settings are user-aware, so they require the current user ID, which you don't have because the request timed out.
> 
> Try this, please: [script.plexmod.zip](https://github.com/user-attachments/files/16349173/script.plexmod.zip)
> 
> It might even fix the wake-sleep issue with waiting for 5 seconds. I believe no timeout was set for certain requests, so depending on your system, that could hang for minutes (which might be what you were experiencing).
> 
> Additionally it retries the myplex account query 4 times if it times out.

Lol, it seems like you discovered the key point of the whole problem now, I tested with restart PM4K it worked normally in the series now, and I tested with wait 5 seconds and it worked normally in all tabs without freezing plex or coreelec, finally. Congratulations! I'll continue using wait 5 seconds, much better.
[log-2024-07-23-13.10.21.zip](https://github.com/user-attachments/files/16349334/log-2024-07-23-13.10.21.zip)

**Comment by pannal** [comment] 2024-07-23 13:13
Awesome. I hoped that to be the case!
